# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  dms:
    build:
      context: ../../src/dms/
      additional_contexts:
        parentdir: ../../src/
    environment:
      ASPNETCORE_HTTP_PORTS: ${DMS_HTTP_PORTS:-8080}
      OAUTH_TOKEN_ENDPOINT: ${OAUTH_TOKEN_ENDPOINT:-http://host.docker.internal:8080/oauth/token}
      NEED_DATABASE_SETUP: ${NEED_DATABASE_SETUP:-true}
      BYPASS_STRING_COERCION: ${BYPASS_STRING_COERCION:-false}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      # Mask incoming HTTP POST and PUT request body structures in DEBUG logging
      MASK_REQUEST_BODY_IN_LOGS: ${MASK_REQUEST_BODY_IN_LOGS:-true}
      MAXIMUM_PAGE_SIZE: ${MAXIMUM_PAGE_SIZE:-500}
      # Segment of the url to use as base for all request. The default path base is deliberately blank on the following line
      PATH_BASE: ${PATH_BASE:-}
      # The default correlation id header is deliberately blank on the following line
      CORRELATION_ID_HEADER: ${CORRELATION_ID_HEADER:-}
      DMS_DATASTORE: ${DMS_DATASTORE:-postgresql}
      DMS_QUERYHANDLER: ${DMS_QUERYHANDLER:-opensearch}
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING:-host=dms-postgresql;port=5432;username=postgres;password=${POSTGRES_PASSWORD};database=${POSTGRES_DB_NAME};}
      DATABASE_ISOLATION_LEVEL: ${DATABASE_ISOLATION_LEVEL:-RepeatableRead}
      # "DATABASE_CONNECTION_STRING_ADMIN_ADMIN" can have alternate credentials with elevated permissions for creating database objects
      DATABASE_CONNECTION_STRING_ADMIN: ${DATABASE_CONNECTION_STRING_ADMIN:-host=dms-postgresql;port=5432;username=postgres;password=${POSTGRES_PASSWORD};database=${POSTGRES_DB_NAME};}
      FAILURE_RATIO: ${FAILURE_RATIO:-0.01}
      SAMPLING_DURATION_SECONDS: ${SAMPLING_DURATION_SECONDS:-10}
      MINIMUM_THROUGHPUT: ${MINIMUM_THROUGHPUT:-2}
      BREAK_DURATION_SECONDS: ${BREAK_DURATION_SECONDS:-30}
      OPENSEARCH_URL: ${OPENSEARCH_URL:-http://dms-search:9200}
      IDENTITY_CLIENT_ROLE: ${IDENTITY_CLIENT_ROLE:-dms-client}
      IDENTITY_AUTHORITY: ${IDENTITY_AUTHORITY:-http://dms-keycloak:8080/realms/edfi}
      IDENTITY_AUDIENCE: ${IDENTITY_AUDIENCE:-account}
      IDENTITY_REQUIRE_HTTPS_METADATA: ${IDENTITY_REQUIRE_HTTPS_METADATA:-false}
      IDENTITY_ROLE_CLAIM_TYPE: ${IDENTITY_ROLE_CLAIM_TYPE:-http://schemas\\.microsoft\\.com/ws/2008/06/identity/claims/role}
      CONFIG_SERVICE_URL: ${CONFIG_SERVICE_URL:-http://dms-config-service:8081}
      CONFIG_SERVICE_CLIENT_ID: ${CONFIG_SERVICE_CLIENT_ID:-CMSAuthMetadataReadOnlyAccess}
      CONFIG_SERVICE_CLIENT_SCOPE: ${CONFIG_SERVICE_CLIENT_SCOPE:-edfi_admin_api/authMetadata_readonly_access}
      CONFIG_SERVICE_CLIENT_SECRET: ${CONFIG_SERVICE_CLIENT_SECRET}
      CACHE_EXPIRATION_MINUTES: ${CACHE_EXPIRATION_MINUTES:-10}
      USE_API_SCHEMA_PATH: ${USE_API_SCHEMA_PATH:-false}
      API_SCHEMA_PATH: ${API_SCHEMA_PATH:-}
    ports:
      - '127.0.0.1:${DMS_HTTP_PORTS}:${DMS_HTTP_PORTS}'
    networks:
      - dms
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:8080/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    hostname: dms

networks:
  dms:
    external: true
