# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: After Pull Request
on:
  workflow_run:
    workflows:
      - "On Pull Request"
    types:
      - completed

permissions: read-all

jobs:
  report-test-results:
    name: Report Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write
      pull-requests: write
      # only needed for private repository
      # contents: read
      # issues: read
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43 # v7
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@f355d34d53ad4e7f506f699478db2dd71da9de5f # v2.15.1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.trx"
