# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      # TODO: restore this later, except run in a PS-specific
      # workflow, so that the C# build and CodeQL do not run
      # unnecessarily.
      # - "**/*.ps1"
      # - "**/*.psm1"
      - "**/*.cs"
      - "**/*.csproj"
      - ".github/**/*.yml"
  workflow_dispatch:

jobs:
  # TODO: restore this later
  run-ps-lint:
    name: PowerShell Linter
    uses: stephenfuqua/Ed-Fi-Actions/.github/workflows/powershell-analyzer.yml@main

  scan-actions-bidi:
    name: Scan Actions, scan all files for BIDI Trojan Attacks
    uses: stephenfuqua/ed-fi-actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-config.json

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:

      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Dependency Review ("Dependabot on PR")
        uses: actions/dependency-review-action@9129d7d40b8c12c1ed0f60400d00c92d437adcce # v4.1.3

      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@cf7e9f23492505046de9a37830c3711dd0f25bb3 # codeql-bundle-v2.16.2
        with:
          languages: csharp

      # Must build the software after initialization of CodeQL; something about
      # CodeQL initialization causes the resulting build to fail unit tests.
      # Therefore rebuilding here, even though also built above.
      - name: Build
        run: ./build.ps1 Build -Configuration Debug

      - name: Perform CodeQL Analysis
        if: success()
        uses: github/codeql-action/analyze@cf7e9f23492505046de9a37830c3711dd0f25bb3 # codeql-bundle-v2.16.2

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: ./build.ps1 Build -Configuration Debug

      - name: Run Unit Tests
        if: success()
        run: ./build.ps1 UnitTest -Configuration Debug

      - name: Upload Test Results
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: unit-tests
          path: "**/*.trx"
          retention-days: 5

  run-e2e-tests:
    name: Run E2E Tests
    needs: run-unit-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: ./build.ps1 Build -Configuration Debug

      - name: Run End to End Tests
        if: success()
        run: ./build.ps1 E2ETest

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: test-logs
          path: |
            ./src/services/EdFi.DataManagementService.Api.Tests.E2E/bin/Debug/net8.0/logs
          retention-days: 10



      - name: Upload Test Results
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: e2e-tests
          path: "**/*.trx"
          retention-days: 5
