# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      # TODO: restore this later, except run in a PS-specific
      # workflow, so that the C# build and CodeQL do not run
      # unnecessarily.
      # - "**/*.ps1"
      # - "**/*.psm1"
      - "**/*.cs"
      - "**/*.csproj"
      - ".github/**/*.yml"
  workflow_dispatch:

jobs:
  # TODO: restore this later
  # run-ps-lint:
  #   name: PowerShell Linter
  #   uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/.github/workflows/powershell-analyzer.yml@main

  scan-actions-bidi:
    name: Scan Actions, scan all files for BIDI Trojan Attacks
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-config.json

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Dependency Review ("Dependabot on PR")
        uses: actions/dependency-review-action@4901385134134e04cec5fbe5ddfe3b2c5bd5d976 # v4.0.0

      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@df32e399139a3050671466d7d9b3cbacc1cfd034 # codeql-bundle-v2.15.2
        with:
          languages: csharp

      # Must build the software after initialization of CodeQL; something about
      # CodeQL initialization causes the resulting build to fail unit tests.
      # Therefore rebuilding here, even though also built above.
      - name: Build
        run: ./build.ps1 Build -Configuration Debug

      - name: Perform CodeQL Analysis
        if: success()
        uses: github/codeql-action/analyze@df32e399139a3050671466d7d9b3cbacc1cfd034 # codeql-bundle-v2.15.2

  run-cs-tests:
    name: Run C# Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: ./build.ps1 Build -Configuration Debug

      - name: Run Unit Tests
        if: success()
        run: ./build.ps1 UnitTest -Configuration Debug

      - name: Upload Test Results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: csharp-tests
          path: "**/*.trx"
          retention-days: 5
